-- MySQL Script generated by MySQL Workbench
-- Fri Apr 15 19:06:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema movies-controll
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema movies-controll
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `movies-controll` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `movies-controll` ;

-- -----------------------------------------------------
-- Table `movies-controll`.`movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies-controll`.`movies` ;

CREATE TABLE IF NOT EXISTS `movies-controll`.`movies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` INT NOT NULL,
  `nome` VARCHAR(30) NOT NULL,
  `total_ep` INT NULL,
  `atual_ep` INT NULL,
  `ultima_view` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
